<?php
//resident images
define("IMAGE_RES_MAX_WIDTH",720);
define("IMAGE_RES_MAX_HEIGHT",480);
define("IMAGE_RES_MEDIUM_WIDTH",360);
define("IMAGE_RES_MEDIUM_HEIGHT",264);
define("IMAGE_RES_THUMB_WIDTH",85);
define("IMAGE_RES_THUMB_HEIGHT",50);

//comment images
define("IMAGE_COMMENT_MAX_WIDTH",1024);
define("IMAGE_COMMENT_MAX_HEIGHT",768);
define("IMAGE_COMMENT_THUMB_WIDTH",400);
define("IMAGE_COMMENT_THUMB_HEIGHT",300);


//area images
define("IMAGE_AREA_MAX_WIDTH",800);
define("IMAGE_AREA_MAX_HEIGHT",600);
define("IMAGE_AREA_MEDIUM_WIDTH",360);
define("IMAGE_AREA_MEDIUM_HEIGHT",264);
define("IMAGE_AREA_THUMB_WIDTH",85);
define("IMAGE_AREA_THUMB_HEIGHT",50);
//artist images
define("IMAGE_ARTIST_MAX_WIDTH",800);
define("IMAGE_ARTIST_MAX_HEIGHT",600);
define("IMAGE_ARTIST_MEDIUM_WIDTH",360);
define("IMAGE_ARTIST_MEDIUM_HEIGHT",264);
define("IMAGE_ARTIST_THUMB_WIDTH",85);
define("IMAGE_ARTIST_THUMB_HEIGHT",50);
//junksale images
define("IMAGE_JUNKSALE_MAX_WIDTH",800);
define("IMAGE_JUNKSALE_MAX_HEIGHT",600);
define("IMAGE_JUNKSALE_MEDIUM_WIDTH",360);
define("IMAGE_JUNKSALE_MEDIUM_HEIGHT",264);
define("IMAGE_JUNKSALE_THUMB_WIDTH",85);
define("IMAGE_JUNKSALE_THUMB_HEIGHT",50);
//artist images
define("IMAGE_CONTRACTOR_MAX_WIDTH",800);
define("IMAGE_CONTRACTOR_MAX_HEIGHT",600);
define("IMAGE_CONTRACTOR_MEDIUM_WIDTH",360);
define("IMAGE_CONTRACTOR_MEDIUM_HEIGHT",264);
define("IMAGE_CONTRACTOR_THUMB_WIDTH",85);
define("IMAGE_CONTRACTOR_THUMB_HEIGHT",50);
?>
